# Generated by Django 4.0.2 on 2022-08-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/uploads/profile_pictures'),
        ),
    ]
